version: '3'

services:
  app:
    build: .
    container_name: XMLfastAPI
    ports:
      - "8080:80"    
    volumes: 
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ${CIFS_PATH_PRICING}
        target: /productpricing
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 80 --workers 1 --reload